### ISSUE TITLE
How Do I add /Contact to craft files? Harvest block questions

### ISSUE THREAD

**Issue by pistols12** [AJCStriker/Movecraft-3#158]
Hello!

I am wondering what do I add to the craft file to get the /contact command. Also, I am trying to use tanks with Harvest blocks, and I cannot figure it out, anyone have a working tank craft file or an example use of the "harvest block" feature?

**Comment by mwkaicz** [comment]
[https://github.com/AJCStriker/Movecraft-3/issues/153#issuecomment-187249938](https://github.com/AJCStriker/Movecraft-3/issues/153#issuecomment-187249938
)
If it is that all, please, close both threads, thx.

**Comment by pistols12** [comment]
What about /contact
