### ISSUE TITLE
How do I allow people to fly in certain region?

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [AJCStriker/Movecraft-3#160]
Title says it all. By enabling "Build", I allow players to place/ break blocks, and I don't want that.
If I don't allow to "Build", they can't fly.

**Comment by mwkaicz** [comment]
[https://github.com/msummers123/Movecraft-3/issues/181](https://github.com/msummers123/Movecraft-3/issues/181)
if that's all, please close both threads, thx.
